### ISSUE TITLE
Connecting GitHub and Trello

### ISSUE THREAD

**Issue by fahad-30** [gamedev-iitk/tower-defense#16]
I used the Trello API, with the help of postman. Got the params and all from https://developer.atlassian.com/cloud/trello/rest/.
HTTP requests in the form of startline, header, body.
Used OAuth1.0 for authorisation, API-key and token is saved in postman.
Id of boards is in Boards>Boards info.
Id for list in Boards>Get list in board, params required = {idBoard}
Id for card in  Lists>Get card in list, params required ={idList}
Create a card in Cards > Create Card, params required ={idList}, other params = {name,desc}

**Comment by mayant15** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Setup Kaka to automatically create a card for new GitHub issues](https://trello.com/c/evNu5ihf/19-setup-kaka-to-automatically-create-a-card-for-new-github-issues)

**Comment by mayant15** [comment]
Done with b4e2e91ab2e7186417ae84d10ebe05d0df408bc9. See #49 for enhancements.
